import { Geist, Geist_Mono ,Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs/";

const inter=Inter({subsets:['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Header/>
          <ConvexClientProvider>
        <main className="container mx-auto pt-16 sm:pt-20" >

          {children}
        </main>
          </ConvexClientProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
